apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq2
  namespace: mq
spec:
  license:
    accept: true
    license: L-CYPF-CRPF3H
    use: Production
  queueManager:
    imagePullPolicy: Always
    storage:
      queueManager:
        enabled: true
    availability:
      type: SingleInstance
    name: QM1
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.4.4.0-r1
  web:
    enabled: true
  pki:
    keys:
      - name: label1
        secret:
          secretName: mq1key
          items:
            - tls.key
            - tls.crt
